import type { Charger, ChargingSession, QueueEntry, Station, UserProfile, Verification } from "@/types/ev";

export const demoUser: UserProfile = {
  id: "user-demo-001",
  name: "Aarav Sharma",
  email: "aarav@example.com",
  phone: "+91 98765 43210",
  vehicleModel: "Tata Nexon EV Max",
  preferredConnector: "CCS2",
  coins: 1280,
  vehicleRangeKm: 215,
  created_at: new Date().toISOString(),
};

export const stations: Station[] = [
  {
    id: "stn-del-001",
    name: "ChargeGrid Connaught Place",
    lat: 28.6315,
    lng: 77.2167,
    address: "Block N, Connaught Place, New Delhi",
    city: "Delhi",
    operator: "ChargeGrid",
    charger_type: "Fast DC",
    connector_types: ["CCS2", "CHAdeMO"],
    total_slots: 8,
    available_slots: 3,
    price_per_kwh: 18,
    status: "open",
    reliability_score: 96,
    last_verified: "12 min ago",
    distance_km: 2.8,
    amenities: ["Cafe", "CCTV", "24x7", "Washroom"],
    wait_minutes: 8,
    peak_hours: "6 PM - 10 PM",
    power_kw: 60,
  },
  {
    id: "stn-del-002",
    name: "VoltWay Saket Select City",
    lat: 28.5288,
    lng: 77.2195,
    address: "A-3 District Centre, Saket, New Delhi",
    city: "Delhi",
    operator: "VoltWay",
    charger_type: "DC",
    connector_types: ["CCS2", "Type 2"],
    total_slots: 6,
    available_slots: 0,
    price_per_kwh: 21,
    status: "busy",
    reliability_score: 88,
    last_verified: "24 min ago",
    distance_km: 9.4,
    amenities: ["Mall", "Security", "Parking"],
    wait_minutes: 34,
    peak_hours: "4 PM - 9 PM",
    power_kw: 50,
  },
  {
    id: "stn-gur-001",
    name: "Ather Point Cyber Hub",
    lat: 28.4957,
    lng: 77.0897,
    address: "Cyber Hub, DLF Cyber City, Gurugram",
    city: "Gurugram",
    operator: "Ather Grid",
    charger_type: "AC",
    connector_types: ["Type 2", "Bharat AC001"],
    total_slots: 10,
    available_slots: 7,
    price_per_kwh: 13,
    status: "open",
    reliability_score: 92,
    last_verified: "7 min ago",
    distance_km: 18.2,
    amenities: ["Food court", "Covered", "WiFi"],
    wait_minutes: 0,
    peak_hours: "1 PM - 5 PM",
    power_kw: 22,
  },
  {
    id: "stn-noi-001",
    name: "Tata Power Sector 18",
    lat: 28.5706,
    lng: 77.3261,
    address: "Near Atta Market, Sector 18, Noida",
    city: "Noida",
    operator: "Tata Power EZ Charge",
    charger_type: "Fast DC",
    connector_types: ["CCS2"],
    total_slots: 5,
    available_slots: 1,
    price_per_kwh: 19,
    status: "open",
    reliability_score: 81,
    last_verified: "1 hr ago",
    distance_km: 12.1,
    amenities: ["Market", "CCTV", "Parking"],
    wait_minutes: 16,
    peak_hours: "5 PM - 11 PM",
    power_kw: 45,
  },
  {
    id: "stn-fbd-001",
    name: "E-Fill Neelam Chowk",
    lat: 28.3919,
    lng: 77.3122,
    address: "Neelam Bata Road, Faridabad",
    city: "Faridabad",
    operator: "E-Fill Electric",
    charger_type: "AC",
    connector_types: ["Type 2"],
    total_slots: 4,
    available_slots: 0,
    price_per_kwh: 12,
    status: "maintenance",
    reliability_score: 64,
    last_verified: "2 days ago",
    distance_km: 27.6,
    amenities: ["Parking"],
    wait_minutes: 0,
    peak_hours: "Closed for service",
    power_kw: 11,
  },
  {
    id: "stn-del-003",
    name: "BluSmart Vasant Kunj Depot",
    lat: 28.5245,
    lng: 77.1587,
    address: "Nelson Mandela Marg, Vasant Kunj, New Delhi",
    city: "Delhi",
    operator: "BluSmart Charge",
    charger_type: "Fast DC",
    connector_types: ["CCS2", "GB/T"],
    total_slots: 16,
    available_slots: 9,
    price_per_kwh: 17,
    status: "open",
    reliability_score: 98,
    last_verified: "4 min ago",
    distance_km: 13.8,
    amenities: ["Fleet bay", "24x7", "CCTV", "Lounge"],
    wait_minutes: 0,
    peak_hours: "10 AM - 2 PM",
    power_kw: 120,
  },
  {
    id: "stn-del-004",
    name: "Statiq India Gate Hub",
    lat: 28.6129,
    lng: 77.2295,
    address: "C-Hexagon, India Gate, New Delhi",
    city: "Delhi",
    operator: "Statiq",
    charger_type: "DC",
    connector_types: ["CCS2", "Type 2"],
    total_slots: 7,
    available_slots: 4,
    price_per_kwh: 20,
    status: "open",
    reliability_score: 90,
    last_verified: "18 min ago",
    distance_km: 4.2,
    amenities: ["Tourist zone", "CCTV", "Food kiosk"],
    wait_minutes: 6,
    peak_hours: "7 PM - 11 PM",
    power_kw: 60,
  },
  {
    id: "stn-gzb-001",
    name: "Jio-bp Indirapuram Mall",
    lat: 28.6368,
    lng: 77.3697,
    address: "Ahinsa Khand, Indirapuram, Ghaziabad",
    city: "Ghaziabad",
    operator: "Jio-bp Pulse",
    charger_type: "Fast DC",
    connector_types: ["CCS2"],
    total_slots: 12,
    available_slots: 5,
    price_per_kwh: 22,
    status: "open",
    reliability_score: 94,
    last_verified: "9 min ago",
    distance_km: 19.7,
    amenities: ["Mall", "Cafe", "Washroom", "Covered"],
    wait_minutes: 11,
    peak_hours: "3 PM - 9 PM",
    power_kw: 90,
  },
  {
    id: "stn-gur-002",
    name: "Shell Recharge Golf Course Road",
    lat: 28.4487,
    lng: 77.0999,
    address: "Sector 54, Golf Course Road, Gurugram",
    city: "Gurugram",
    operator: "Shell Recharge",
    charger_type: "Fast DC",
    connector_types: ["CCS2", "CHAdeMO", "Type 2"],
    total_slots: 6,
    available_slots: 2,
    price_per_kwh: 24,
    status: "open",
    reliability_score: 91,
    last_verified: "32 min ago",
    distance_km: 22.4,
    amenities: ["Fuel station", "Cafe", "Air", "CCTV"],
    wait_minutes: 20,
    peak_hours: "8 AM - 11 AM",
    power_kw: 150,
  },
  {
    id: "stn-noi-002",
    name: "EESL Botanical Garden Metro",
    lat: 28.5642,
    lng: 77.3342,
    address: "Botanical Garden Metro Parking, Noida",
    city: "Noida",
    operator: "EESL",
    charger_type: "AC",
    connector_types: ["Bharat AC001", "Type 2"],
    total_slots: 9,
    available_slots: 6,
    price_per_kwh: 11,
    status: "open",
    reliability_score: 83,
    last_verified: "45 min ago",
    distance_km: 13.6,
    amenities: ["Metro", "Parking", "Security"],
    wait_minutes: 0,
    peak_hours: "9 AM - 12 PM",
    power_kw: 15,
  },
  {
    id: "stn-del-005",
    name: "BSES Rajouri Garden Plaza",
    lat: 28.6422,
    lng: 77.1164,
    address: "Najafgarh Road, Rajouri Garden, New Delhi",
    city: "Delhi",
    operator: "BSES EV",
    charger_type: "DC",
    connector_types: ["CCS2"],
    total_slots: 5,
    available_slots: 0,
    price_per_kwh: 16,
    status: "busy",
    reliability_score: 79,
    last_verified: "2 hr ago",
    distance_km: 11.8,
    amenities: ["Market", "Parking"],
    wait_minutes: 42,
    peak_hours: "6 PM - 10 PM",
    power_kw: 30,
  },
  {
    id: "stn-grn-001",
    name: "Yamuna Expressway EV Plaza",
    lat: 28.4595,
    lng: 77.5047,
    address: "Knowledge Park II, Greater Noida",
    city: "Greater Noida",
    operator: "Highway Charge",
    charger_type: "Fast DC",
    connector_types: ["CCS2", "GB/T"],
    total_slots: 14,
    available_slots: 10,
    price_per_kwh: 18,
    status: "open",
    reliability_score: 89,
    last_verified: "27 min ago",
    distance_km: 31.5,
    amenities: ["Highway", "Food court", "Lounge", "24x7"],
    wait_minutes: 0,
    peak_hours: "6 AM - 10 AM",
    power_kw: 120,
  },
  ...buildBhopalStations(),
];

/**
 * Generates ~28 charging stations spread across Bhopal neighbourhoods.
 * Kept as a function so the area list stays editable in one place.
 */
function buildBhopalStations(): Station[] {
  const base: Array<{ name: string; area: string; lat: number; lng: number; op: string; type: ChargerType; kw: number; slots: number; price: number; conns: string[]; amenities: string[] }> = [
    { name: "ChargeGrid MP Nagar Zone-1", area: "MP Nagar, Bhopal", lat: 23.2330, lng: 77.4347, op: "ChargeGrid", type: "Fast DC", kw: 60, slots: 6, price: 18, conns: ["CCS2", "CHAdeMO"], amenities: ["Cafe", "24x7", "CCTV"] },
    { name: "Tata Power DB City Mall", area: "DB City Mall, Arera Hills", lat: 23.2389, lng: 77.4302, op: "Tata Power EZ Charge", type: "Fast DC", kw: 90, slots: 8, price: 19, conns: ["CCS2"], amenities: ["Mall", "Food court", "Washroom"] },
    { name: "Statiq New Market Hub", area: "New Market, TT Nagar", lat: 23.2348, lng: 77.4014, op: "Statiq", type: "DC", kw: 50, slots: 5, price: 20, conns: ["CCS2", "Type 2"], amenities: ["Market", "Parking"] },
    { name: "Jio-bp Aura Mall", area: "Hoshangabad Road, Bhopal", lat: 23.2034, lng: 77.4675, op: "Jio-bp Pulse", type: "Fast DC", kw: 120, slots: 10, price: 21, conns: ["CCS2", "GB/T"], amenities: ["Mall", "Cafe", "Covered"] },
    { name: "BHEL Township Charge Point", area: "BHEL, Piplani", lat: 23.2696, lng: 77.5061, op: "BHEL EV", type: "AC", kw: 22, slots: 6, price: 13, conns: ["Type 2", "Bharat AC001"], amenities: ["Township", "Security"] },
    { name: "Ather Grid Arera Colony", area: "E-7, Arera Colony", lat: 23.2189, lng: 77.4356, op: "Ather Grid", type: "AC", kw: 22, slots: 4, price: 14, conns: ["Type 2"], amenities: ["Cafe", "Covered"] },
    { name: "Shell Recharge Habibganj", area: "Habibganj, Bhopal", lat: 23.2293, lng: 77.4361, op: "Shell Recharge", type: "Fast DC", kw: 150, slots: 4, price: 24, conns: ["CCS2", "CHAdeMO"], amenities: ["Fuel station", "Air", "CCTV"] },
    { name: "BluSmart Bittan Market Depot", area: "Bittan Market", lat: 23.2299, lng: 77.4406, op: "BluSmart Charge", type: "Fast DC", kw: 60, slots: 8, price: 17, conns: ["CCS2"], amenities: ["Fleet bay", "24x7"] },
    { name: "EESL Bhopal Junction", area: "Bhopal Railway Stn", lat: 23.2685, lng: 77.4116, op: "EESL", type: "AC", kw: 15, slots: 6, price: 11, conns: ["Bharat AC001"], amenities: ["Station", "Parking"] },
    { name: "VoltWay Kolar Dam Road", area: "Kolar Road, Bhopal", lat: 23.1620, lng: 77.4300, op: "VoltWay", type: "DC", kw: 50, slots: 4, price: 19, conns: ["CCS2", "Type 2"], amenities: ["Highway", "Cafe"] },
    { name: "ChargeZone AIIMS Bhopal", area: "AIIMS, Saket Nagar", lat: 23.2061, lng: 77.4641, op: "ChargeZone", type: "Fast DC", kw: 60, slots: 6, price: 18, conns: ["CCS2"], amenities: ["Hospital", "24x7", "Security"] },
    { name: "BSES Shahpura Lake View", area: "Shahpura, Bhopal", lat: 23.1926, lng: 77.4404, op: "BSES EV", type: "DC", kw: 30, slots: 4, price: 16, conns: ["CCS2"], amenities: ["Lake side", "Parking"] },
    { name: "Tata Power Bairagarh", area: "Bairagarh, Bhopal", lat: 23.2828, lng: 77.3324, op: "Tata Power EZ Charge", type: "AC", kw: 22, slots: 4, price: 13, conns: ["Type 2"], amenities: ["Highway", "Parking"] },
    { name: "Jio-bp Govindpura Industrial", area: "Govindpura, Bhopal", lat: 23.2650, lng: 77.4798, op: "Jio-bp Pulse", type: "Fast DC", kw: 90, slots: 6, price: 20, conns: ["CCS2"], amenities: ["Industrial", "24x7"] },
    { name: "Statiq Misrod Square", area: "Misrod, Bhopal", lat: 23.1812, lng: 77.4998, op: "Statiq", type: "DC", kw: 60, slots: 4, price: 19, conns: ["CCS2", "Type 2"], amenities: ["Highway", "Food kiosk"] },
    { name: "ChargeGrid Mandideep MIDC", area: "Mandideep Industrial", lat: 23.1056, lng: 77.5180, op: "ChargeGrid", type: "Fast DC", kw: 120, slots: 8, price: 18, conns: ["CCS2", "GB/T"], amenities: ["Industrial", "Lounge"] },
    { name: "Ather Grid IT Park Badwai", area: "Bhopal IT Park", lat: 23.2882, lng: 77.4612, op: "Ather Grid", type: "AC", kw: 22, slots: 8, price: 13, conns: ["Type 2"], amenities: ["Office", "WiFi"] },
    { name: "VoltWay MANIT Campus", area: "MANIT, Bhopal", lat: 23.2148, lng: 77.4071, op: "VoltWay", type: "AC", kw: 22, slots: 4, price: 12, conns: ["Type 2", "Bharat AC001"], amenities: ["Campus"] },
    { name: "ChargeZone ISBT Hub", area: "ISBT, Habibganj", lat: 23.2253, lng: 77.4423, op: "ChargeZone", type: "Fast DC", kw: 60, slots: 6, price: 18, conns: ["CCS2"], amenities: ["Bus terminal", "24x7"] },
    { name: "Shell Recharge 10 No. Market", area: "10 No. Market, Bhopal", lat: 23.2310, lng: 77.4108, op: "Shell Recharge", type: "DC", kw: 50, slots: 3, price: 21, conns: ["CCS2"], amenities: ["Market", "Cafe"] },
    { name: "BluSmart Indrapuri Depot", area: "Indrapuri, BHEL", lat: 23.2604, lng: 77.4934, op: "BluSmart Charge", type: "Fast DC", kw: 60, slots: 6, price: 17, conns: ["CCS2"], amenities: ["Fleet bay"] },
    { name: "EESL Awadhpuri Square", area: "Awadhpuri, Bhopal", lat: 23.2542, lng: 77.5008, op: "EESL", type: "AC", kw: 15, slots: 4, price: 11, conns: ["Bharat AC001"], amenities: ["Public"] },
    { name: "Tata Power Karond Square", area: "Karond, Bhopal", lat: 23.3044, lng: 77.3834, op: "Tata Power EZ Charge", type: "DC", kw: 30, slots: 3, price: 16, conns: ["CCS2"], amenities: ["Junction"] },
    { name: "ChargeGrid Berasia Road", area: "Berasia Road, Bhopal", lat: 23.3199, lng: 77.4012, op: "ChargeGrid", type: "AC", kw: 22, slots: 4, price: 13, conns: ["Type 2"], amenities: ["Highway"] },
    { name: "Jio-bp Hoshangabad Bypass", area: "Hoshangabad Bypass", lat: 23.1582, lng: 77.4870, op: "Jio-bp Pulse", type: "Fast DC", kw: 120, slots: 6, price: 21, conns: ["CCS2", "CHAdeMO"], amenities: ["Highway", "24x7", "Cafe"] },
    { name: "Statiq Gandhinagar Plaza", area: "Gandhinagar, Bhopal", lat: 23.2906, lng: 77.4019, op: "Statiq", type: "DC", kw: 50, slots: 4, price: 19, conns: ["CCS2"], amenities: ["Plaza", "Parking"] },
    { name: "ChargeZone Rajiv Gandhi Bhawan", area: "Bittan Market", lat: 23.2278, lng: 77.4488, op: "ChargeZone", type: "Fast DC", kw: 60, slots: 5, price: 18, conns: ["CCS2"], amenities: ["Govt office"] },
    { name: "VoltWay Lalghati Square", area: "Lalghati, Bhopal", lat: 23.2731, lng: 77.3784, op: "VoltWay", type: "AC", kw: 22, slots: 4, price: 13, conns: ["Type 2"], amenities: ["Junction", "Parking"] },
  ];
  return base.map((b, i) => {
    const total = b.slots;
    const avail = (i % 5 === 0) ? 0 : Math.max(1, total - ((i % total) + 1));
    return {
      id: `stn-bho-${(i + 1).toString().padStart(3, "0")}`,
      name: b.name,
      lat: b.lat,
      lng: b.lng,
      address: b.area,
      city: "Bhopal",
      operator: b.op,
      charger_type: b.type,
      connector_types: b.conns,
      total_slots: total,
      available_slots: avail,
      price_per_kwh: b.price,
      status: avail === 0 ? "busy" : "open",
      reliability_score: 78 + ((i * 3) % 20),
      last_verified: `${5 + ((i * 7) % 55)} min ago`,
      distance_km: Number((1 + ((i * 1.7) % 18)).toFixed(1)),
      amenities: b.amenities,
      wait_minutes: avail === 0 ? 20 + (i % 25) : (i % 12),
      peak_hours: "6 PM - 10 PM",
      power_kw: b.kw,
    } satisfies Station;
  });
}

export const chargers: Charger[] = stations.flatMap((station) =>
  Array.from({ length: station.total_slots }, (_, index) => ({
    id: `${station.id}-ch-${index + 1}`,
    station_id: station.id,
    status: index < station.available_slots ? "available" : station.status === "maintenance" ? "offline" : "occupied",
    type: station.charger_type,
    connector: station.connector_types[index % station.connector_types.length] ?? (station.charger_type === "AC" ? "Type 2" : "CCS2"),
    power_kw: station.power_kw,
  })),
);

export const queueEntries: QueueEntry[] = [
  { id: "q-1", station_id: "stn-del-001", user_id: "u-2", user_name: "Neha", position: 1, status: "next", eta_minutes: 2, created_at: new Date().toISOString() },
  { id: "q-2", station_id: "stn-del-001", user_id: "u-3", user_name: "Kabir", position: 2, status: "waiting", eta_minutes: 18, created_at: new Date().toISOString() },
  { id: "q-3", station_id: "stn-del-002", user_id: "u-4", user_name: "Meera", position: 1, status: "waiting", eta_minutes: 14, created_at: new Date().toISOString() },
  { id: "q-4", station_id: "stn-noi-001", user_id: "u-5", user_name: "Rohan", position: 1, status: "next", eta_minutes: 5, created_at: new Date().toISOString() },
  { id: "q-5", station_id: "stn-del-005", user_id: "u-9", user_name: "Ananya", position: 1, status: "charging", eta_minutes: 24, created_at: new Date().toISOString() },
  { id: "q-6", station_id: "stn-del-005", user_id: "u-10", user_name: "Ishaan", position: 2, status: "waiting", eta_minutes: 42, created_at: new Date().toISOString() },
  { id: "q-7", station_id: "stn-gzb-001", user_id: "u-11", user_name: "Fatima", position: 1, status: "next", eta_minutes: 7, created_at: new Date().toISOString() },
];

export const sessions: ChargingSession[] = [
  { id: "s-1", user_id: demoUser.id, station_id: "stn-del-001", start_time: new Date(Date.now() - 24 * 60 * 1000).toISOString(), energy_used: 18.4, cost: 331.2, status: "active" },
  { id: "s-2", user_id: "u-8", station_id: "stn-del-003", start_time: new Date(Date.now() - 84 * 60 * 1000).toISOString(), end_time: new Date(Date.now() - 18 * 60 * 1000).toISOString(), energy_used: 31.1, cost: 528.7, status: "paid" },
  { id: "s-3", user_id: "u-12", station_id: "stn-gur-002", start_time: new Date(Date.now() - 64 * 60 * 1000).toISOString(), energy_used: 42.6, cost: 1022.4, status: "completed" },
  { id: "s-4", user_id: "u-13", station_id: "stn-gzb-001", start_time: new Date(Date.now() - 34 * 60 * 1000).toISOString(), energy_used: 26.2, cost: 576.4, status: "active" },
];

export const verifications: Verification[] = [
  { id: "v-1", station_id: "stn-del-001", user_id: "u-2", status: "working", cable_condition: "excellent", created_at: new Date().toISOString() },
  { id: "v-2", station_id: "stn-fbd-001", user_id: "u-6", status: "not_working", cable_condition: "damaged", created_at: new Date(Date.now() - 2 * 86400000).toISOString() },
  { id: "v-3", station_id: "stn-gzb-001", user_id: "u-11", status: "working", cable_condition: "usable", created_at: new Date(Date.now() - 45 * 60000).toISOString() },
  { id: "v-4", station_id: "stn-noi-002", user_id: "u-15", status: "working", cable_condition: "excellent", created_at: new Date(Date.now() - 3 * 3600000).toISOString() },
];
