import type { Charger, ChargingSession, QueueEntry, Station, UserProfile, Verification } from "@/types/ev";

export const demoUser: UserProfile = {
  id: "user-demo-001",
  name: "Aarav Sharma",
  email: "aarav@example.com",
  coins: 1280,
  vehicleRangeKm: 215,
  created_at: new Date().toISOString(),
};

export const stations: Station[] = [
  {
    id: "stn-del-001",
    name: "ChargeGrid Connaught Place",
    lat: 28.6315,
    lng: 77.2167,
    address: "Block N, Connaught Place, New Delhi",
    city: "Delhi",
    charger_type: "Fast DC",
    total_slots: 8,
    available_slots: 3,
    price_per_kwh: 18,
    status: "open",
    reliability_score: 96,
    last_verified: "12 min ago",
    distance_km: 2.8,
    amenities: ["Cafe", "CCTV", "24x7", "Washroom"],
    wait_minutes: 8,
  },
  {
    id: "stn-del-002",
    name: "VoltWay Saket Select City",
    lat: 28.5288,
    lng: 77.2195,
    address: "A-3 District Centre, Saket, New Delhi",
    city: "Delhi",
    charger_type: "DC",
    total_slots: 6,
    available_slots: 0,
    price_per_kwh: 21,
    status: "busy",
    reliability_score: 88,
    last_verified: "24 min ago",
    distance_km: 9.4,
    amenities: ["Mall", "Security", "Parking"],
    wait_minutes: 34,
  },
  {
    id: "stn-gur-001",
    name: "Ather Point Cyber Hub",
    lat: 28.4957,
    lng: 77.0897,
    address: "Cyber Hub, DLF Cyber City, Gurugram",
    city: "Gurugram",
    charger_type: "AC",
    total_slots: 10,
    available_slots: 7,
    price_per_kwh: 13,
    status: "open",
    reliability_score: 92,
    last_verified: "7 min ago",
    distance_km: 18.2,
    amenities: ["Food court", "Covered", "WiFi"],
    wait_minutes: 0,
  },
  {
    id: "stn-noi-001",
    name: "Tata Power Sector 18",
    lat: 28.5706,
    lng: 77.3261,
    address: "Near Atta Market, Sector 18, Noida",
    city: "Noida",
    charger_type: "Fast DC",
    total_slots: 5,
    available_slots: 1,
    price_per_kwh: 19,
    status: "open",
    reliability_score: 81,
    last_verified: "1 hr ago",
    distance_km: 12.1,
    amenities: ["Market", "CCTV", "Parking"],
    wait_minutes: 16,
  },
  {
    id: "stn-fbd-001",
    name: "E-Fill Neelam Chowk",
    lat: 28.3919,
    lng: 77.3122,
    address: "Neelam Bata Road, Faridabad",
    city: "Faridabad",
    charger_type: "AC",
    total_slots: 4,
    available_slots: 0,
    price_per_kwh: 12,
    status: "maintenance",
    reliability_score: 64,
    last_verified: "2 days ago",
    distance_km: 27.6,
    amenities: ["Parking"],
    wait_minutes: 0,
  },
  {
    id: "stn-del-003",
    name: "BluSmart Vasant Kunj Depot",
    lat: 28.5245,
    lng: 77.1587,
    address: "Nelson Mandela Marg, Vasant Kunj, New Delhi",
    city: "Delhi",
    charger_type: "Fast DC",
    total_slots: 16,
    available_slots: 9,
    price_per_kwh: 17,
    status: "open",
    reliability_score: 98,
    last_verified: "4 min ago",
    distance_km: 13.8,
    amenities: ["Fleet bay", "24x7", "CCTV", "Lounge"],
    wait_minutes: 0,
  },
];

export const chargers: Charger[] = stations.flatMap((station) =>
  Array.from({ length: station.total_slots }, (_, index) => ({
    id: `${station.id}-ch-${index + 1}`,
    station_id: station.id,
    status: index < station.available_slots ? "available" : station.status === "maintenance" ? "offline" : "occupied",
    type: station.charger_type,
    connector: station.charger_type === "AC" ? "Type 2" : "CCS2",
  })),
);

export const queueEntries: QueueEntry[] = [
  { id: "q-1", station_id: "stn-del-001", user_id: "u-2", user_name: "Neha", position: 1, status: "next", eta_minutes: 2, created_at: new Date().toISOString() },
  { id: "q-2", station_id: "stn-del-001", user_id: "u-3", user_name: "Kabir", position: 2, status: "waiting", eta_minutes: 18, created_at: new Date().toISOString() },
  { id: "q-3", station_id: "stn-del-002", user_id: "u-4", user_name: "Meera", position: 1, status: "waiting", eta_minutes: 14, created_at: new Date().toISOString() },
  { id: "q-4", station_id: "stn-noi-001", user_id: "u-5", user_name: "Rohan", position: 1, status: "next", eta_minutes: 5, created_at: new Date().toISOString() },
];

export const sessions: ChargingSession[] = [
  { id: "s-1", user_id: demoUser.id, station_id: "stn-del-001", start_time: new Date(Date.now() - 24 * 60 * 1000).toISOString(), energy_used: 18.4, cost: 331.2, status: "active" },
  { id: "s-2", user_id: "u-8", station_id: "stn-del-003", start_time: new Date(Date.now() - 84 * 60 * 1000).toISOString(), end_time: new Date(Date.now() - 18 * 60 * 1000).toISOString(), energy_used: 31.1, cost: 528.7, status: "paid" },
];

export const verifications: Verification[] = [
  { id: "v-1", station_id: "stn-del-001", user_id: "u-2", status: "working", cable_condition: "excellent", created_at: new Date().toISOString() },
  { id: "v-2", station_id: "stn-fbd-001", user_id: "u-6", status: "not_working", cable_condition: "damaged", created_at: new Date(Date.now() - 2 * 86400000).toISOString() },
];
